// react/frontend/src/container/Contact/Contact.jsx
import { useState } from 'react';

import { images } from '../../constants';
import { AppWrap, MotionWrap } from '../../wrapper';
import { motion } from 'framer-motion';

import { client } from '../../client';

import './Contact.scss';


const Contact = () => {
  const [formData, setFormData] = useState({ name: '', email: '', message: '' });
  const [isFormSubmitted, setIsFormSubmitted] = useState(false);
  const [loading, setLoading] = useState(false);
  const [errors, setErrors] = useState({}); // State to store input validation errors

  const { name, email, message } = formData;

  const handleChangeInput = (e) => {
    const { name, value } = e.target;
    setFormData({ ...formData, [name]: value });
  };

  const handleSubmit = () => {
    // Clear previous errors
    setErrors({});

    // Perform input validation
    const validationErrors = {};
    if (!name.trim()) {
      validationErrors.name = 'Name is required';
    }
    if (!email.trim()) {
      validationErrors.email = 'Email is required';
    } else if (!/\S+@\S+\.\S+/.test(email)) {
      validationErrors.email = 'Invalid email format';
    }
    if (!message.trim()) {
      validationErrors.message = 'Message is required';
    }

    // If there are validation errors, set them and return
    if (Object.keys(validationErrors).length > 0) {
      setErrors(validationErrors);
      return;
    }

    setLoading(true);

    // Submit form data
    const contact = {
      _type: 'contact',
      name: formData.name,
      email: formData.email,
      message: formData.message,
    };

    client.create(contact)
      .then(() => {
        setLoading(false);
        setIsFormSubmitted(true);
      })
      .catch((err) => console.log(err));
  };

  return (
    <>
      <h2 className="head-text">chat with <span> me</span></h2>
      <div className="app__contact-cards">
        <motion.div
          whileHover={{ scale: 1.2 }}
          transition={{ duration: 0.2, type: 'tween' }}
          className="app__contact-card"
        >
          <img src={images.email} alt="email" />
          <a href="mailto:aanujkhurana@gmail.com" className="p-text">aanujkhurana@gmail.com</a>
        </motion.div>
        <motion.div
          whileHover={{ scale: 1.2 }}
          transition={{ duration: 0.2, type: 'tween' }}
          className="app__contact-card"
        >
          <img src={images.mobile} alt="phone" />
          <a href="tel:+61 (481) 25-0988" className="p-text">(+61)  48-125-0988</a>
        </motion.div>
      </div>
      
      {!isFormSubmitted ? (
        <div className="app__contact-form app__flex">
          <div className="app__flex">
            <input className="p-text" type="text" placeholder="Your Name" name="name" value={name} onChange={handleChangeInput} />
          </div>
          <div>
            {errors.name && <span className="form-error">{errors.name}</span> }
          </div>
          <div className="app__flex">
            <input className="p-text" type="email" placeholder="Your Email" name="email" value={email} onChange={handleChangeInput} />
          </div>
          <div>
            {errors.email && <span className="form-error">{errors.email}</span> }
          </div>
          <div>
            <textarea
              className="p-text"
              placeholder="Your Message"
              value={message}
              name="message"
              onChange={handleChangeInput}
            />
          </div>
          <div>
            {errors.message && <span className="form-error">{errors.message}</span>}
          </div>
          <button type="button" className="p-text" onClick={handleSubmit}>{!loading ? 'Send Message' : 'Sending...'}</button>
        </div>
      ) : 
      (
        <div>
          <h3 className="head-text">
            <span>Thank you!</span> for getting in touch.
          </h3>
        </div>
      )}
    </>
  )
}

export default AppWrap(
  MotionWrap(Contact, 'app__contact'),
  'contact',
  'app__primarybg',
);

// frontend/src/components/Contact.vue
<template>
  <header>
    <h2 class="h2 article-title">Contact</h2>
  </header>
  <section class="contact-form">
    <form @submit.prevent="handleSubmit" class="form" data-form>
      <div class="input-wrapper">
        <input
          type="text"
          name="name"
          v-model="formData.name"
          class="form-input"
          placeholder="Full name"
          required
          data-form-input
        />
        <span v-if="errors.name" class="form-error">{{ errors.name }}</span>

        <input
          type="email"
          name="email"
          v-model="formData.email"
          class="form-input"
          placeholder="Email address"
          required
          data-form-input
        />
        <span v-if="errors.email" class="form-error">{{ errors.email }}</span>
      </div>

      <textarea
        name="message"
        v-model="formData.message"
        class="form-input"
        placeholder="Your Message"
        required
        data-form-input
      ></textarea>
      <span v-if="errors.message" class="form-error">{{ errors.message }}</span>

      <button class="form-btn" type="submit" :disabled="loading" data-form-btn>
        <ion-icon name="paper-plane"></ion-icon>
        <span>{{ loading ? "Sending..." : "Send Message" }}</span>
      </button>

      <p v-if="isFormSubmitted" class="form-success">Thank you for your message!</p>
    </form>
  </section>

  <header>
    <h2 class="h2 article-title">Location</h2>
  </header>
  <section class="mapbox" data-mapbox>
    <figure>
      <iframe
        src="https://www.google.com/maps/embed/v1/place?q=parkwood&key=AIzaSyBFw0Qbyq9zTFTd-tUY6dZWTgaQzuU17R8"
        width="400"
        height="300"
        loading="lazy"
      ></iframe>
    </figure>
  </section>
</template>

<script setup>
import { ref } from "vue";
import { client } from "../lib/client";

const formData = ref({ name: "", email: "", message: "" });
const isFormSubmitted = ref(false);
const loading = ref(false);
const errors = ref({});

const handleSubmit = () => {
  errors.value = {};
  const { name, email, message } = formData.value;
  const validationErrors = {};

  if (!name.trim()) validationErrors.name = "Name is required";
  if (!email.trim()) {
    validationErrors.email = "Email is required";
  } else if (!/\S+@\S+\.\S+/.test(email)) {
    validationErrors.email = "Invalid email format";
  }
  if (!message.trim()) validationErrors.message = "Message is required";

  if (Object.keys(validationErrors).length > 0) {
    errors.value = validationErrors;
    return;
  }

  loading.value = true;

  const contact = {
    _type: "contact",
    name: formData.value.name,
    email: formData.value.email,
    message: formData.value.message,
  };

  client
    .create(contact)
    .then(() => {
      loading.value = false;
      isFormSubmitted.value = true;
      formData.value = { name: "", email: "", message: "" };
    })
    .catch((err) => {
      console.error(err);
      loading.value = false;
      formData.value = { name: "", email: "", message: "" };
    });
};
</script>

<style scoped>
.form-error {
  color: red;
  font-size: 0.875rem;
  margin-top: -10px;
  margin-bottom: 10px;
}

.form-success {
  color: green;
  font-size: 1rem;
  margin-top: 10px;
}
</style>
